# Generated by Django 5.2.11 on 2026-02-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournamentteam_school_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='potential_score',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Potential Score'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Current Score'),
        ),
    ]
