# Generated by Django 5.2.11 on 2026-02-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_entry_still_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='potential_score',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Optimistic Max Potential Score'),
        ),
    ]
