# Generated by Django 5.2.11 on 2026-02-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournamentteam_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
