# Generated by Django 5.2.11 on 2026-02-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_entry_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='school_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournament.school'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
