# Generated by Django 5.2.11 on 2026-02-14 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_entry_potential_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='Dummy Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('name', 'user', 'tournament')},
        ),
    ]
