# Generated by Django 5.2.11 on 2026-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_entry_unique_together_entry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='current_rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Rank'),
        ),
        migrations.AddField(
            model_name='entry',
            name='max_potential_rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Potential Rank'),
        ),
    ]
