# Generated by Django 5.2.11 on 2026-03-01 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_entry_current_rank_entry_max_potential_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='concluded',
            field=models.BooleanField(default=False, help_text='Tournament has concluded'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournament.tournament'),
        ),
    ]
