# Generated by Django 5.2.11 on 2026-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournament_concluded_alter_entry_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
