# Generated by Django 5.2.11 on 2026-03-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_alter_school_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'school', 'school_secondary'), ('tournament', 'seed', 'region')},
        ),
    ]
