# Generated by Django 5.2.11 on 2026-03-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_tournamentteam_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'school'), ('tournament', 'seed', 'region')},
        ),
    ]
