# Generated by Django 5.2.11 on 2026-03-02 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_tournamentteam_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='seed',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='wins',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
