# Generated by Django 5.2.11 on 2026-03-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_alter_tournamentteam_seed_alter_tournamentteam_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payment Received'),
        ),
    ]
