# Generated by Django 5.2.11 on 2026-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_entry_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='standings_last_updated_at',
            field=models.DateTimeField(help_text="The last time a tournament's standings were updated by an admin", null=True),
        ),
    ]
