# Generated by Django 5.2.11 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_tournament_standings_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='standings_last_updated_at',
            field=models.DateTimeField(blank=True, help_text="The last time a tournament's standings were updated by an admin", null=True),
        ),
    ]
