# Generated by Django 5.2.11 on 2026-08-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_alter_tournament_standings_last_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentteam',
            options={'ordering': ('region', 'seed')},
        ),
    ]
