# Generated by Django 5.2.11 on 2026-02-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='school_secondary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournament.school'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='region',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('South', 'South'), ('Midwest', 'Midwest')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_appearances', to='tournament.school'),
        ),
    ]
