# Generated by Django 5.2.11 on 2026-02-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentteam_school_secondary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'school', 'school_secondary')},
        ),
    ]
