# Generated by Django 5.2.11 on 2026-02-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_entry_potential_score_alter_entry_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='still_alive',
            field=models.BooleanField(default=True, verbose_name='Still Alive'),
        ),
    ]
